# Generated by Django 3.1.1 on 2020-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField(default=305355356)),
                ('request_id', models.IntegerField(default=1234)),
                ('date', models.DateField(auto_now=True)),
                ('pickup_time', models.TimeField(auto_now=True)),
                ('drop_off_time', models.TimeField(auto_now=True)),
                ('item', models.CharField(choices=[('20009', 'closet'), ('20016', 'bed'), ('20008', 'chair'), ('10006', 'fridge'), ('10029', 'Washing machine'), ('20017', 'sofa')], max_length=40)),
                ('pickup_location', models.CharField(choices=[('Tel Aviv', 'Tel Aviv'), ('Jerusalem', 'Jerusalem'), ('Beer Sheva', 'Beer Sheva'), ('Haifa', 'Haifa'), ('Modiin', 'Modiin'), ('Hasharon', 'Hasharon')], max_length=40)),
                ('drop_off_location', models.CharField(choices=[('Tel Aviv', 'Tel Aviv'), ('Jerusalem', 'Jerusalem'), ('Beer Sheva', 'Beer Sheva'), ('Haifa', 'Haifa'), ('Modiin', 'Modiin'), ('Hasharon', 'Hasharon')], max_length=40)),
                ('status', models.CharField(choices=[('coordinated', 'coordinated'), ('waiting', 'waiting')], default='waiting', max_length=40)),
            ],
        ),
    ]
