# Generated by Django 3.1 on 2020-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField(default=305355356)),
                ('request_id', models.IntegerField(default=1234)),
                ('pickup_time', models.DateTimeField()),
                ('item', models.CharField(choices=[('table', 'table'), ('bed', 'bed'), ('TV', 'TV'), ('washing machine', 'washing machine'), ('fridge', 'fridge'), ('oven', 'oven'), ('microwave oven', 'microwave oven'), ('chair', 'chair'), ('computer screen', 'computer screen'), ('keyboard', 'keyboard'), ('laptop', 'laptop'), ('closet', 'closet')], max_length=40)),
                ('region_pick_up', models.CharField(choices=[('Tel Aviv', 'Tel Aviv'), ('Jerusalem', 'Jerusalem'), ('Beer Sheva', 'Beer Sheva'), ('Haifa', 'Haifa'), ('Modiin', 'Modiin'), ('Hasharon', 'Hasharon')], max_length=40)),
                ('region_drop_of', models.CharField(choices=[('Tel Aviv', 'Tel Aviv'), ('Jerusalem', 'Jerusalem'), ('Beer Sheva', 'Beer Sheva'), ('Haifa', 'Haifa'), ('Modiin', 'Modiin'), ('Hasharon', 'Hasharon')], max_length=40)),
                ('status', models.CharField(choices=[('coordinated', 'coordinated'), ('waiting', 'waiting')], default='waiting', max_length=40)),
            ],
        ),
    ]
