# Generated by Django 3.1 on 2020-09-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinateditems',
            old_name='region_drop_of',
            new_name='drop_off_location',
        ),
        migrations.RenameField(
            model_name='coordinateditems',
            old_name='region_pick_up',
            new_name='pickup_location',
        ),
        migrations.AddField(
            model_name='coordinateditems',
            name='drop_off_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coordinateditems',
            name='pickup_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
