# Generated by Django 3.1.1 on 2020-09-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinateditems',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coordinateditems',
            name='drop_off_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='coordinateditems',
            name='pickup_time',
            field=models.TimeField(),
        ),
    ]
