# Generated by Django 3.1.1 on 2020-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinateditems',
            name='friend_id',
            field=models.CharField(default=305355356, max_length=40),
        ),
    ]
