# Generated by Django 3.1 on 2020-09-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate', '0002_auto_20200903_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinateditems',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
